export const ErrorCode = {
  MISSING_AGENT_ID: 'MISSING_AGENT_ID',
  MISSING_FIELDS: 'MISSING_FIELDS',
  NO_ADAPTER: 'NO_ADAPTER',
  ADAPTER_NO_STOP: 'ADAPTER_NO_STOP',
  AGENT_NOT_FOUND: 'AGENT_NOT_FOUND',
  MACHINE_NOT_FOUND: 'MACHINE_NOT_FOUND',
  SPAWN_FAILED: 'SPAWN_FAILED',
  STOP_FAILED: 'STOP_FAILED',
  REMOTE_UNREACHABLE: 'REMOTE_UNREACHABLE',
} as const;
